apiVersion: v1
kind: ConfigMap
metadata:
  name: finance-tracker-config
  namespace: finance-tracker-dev
data:
  GMAIL_TOKEN_FILE: "token.json"
  RABBITMQ_HOST: "192.168.20.70"
  RABBITMQ_EXCHANGE: "finance-tracker-dev.events"
  RABBITMQ_VHOST: "/finance-tracker-dev"
  SYNC_INTERVAL_MINUTES: "15"
  OLLAMA_BASE_URL: "http://192.168.20.80:11434"
  OLLAMA_MODEL: "qwen2.5:3b"
  BACKEND_URL: "http://finance-tracker-backend:8000"
  PYTHONUNBUFFERED: "1"