apiVersion: secrets.hashicorp.com/v1beta1
kind: VaultStaticSecret
metadata:
  name: finance-tracker
spec:
  type: kv-v2
  vaultConnectionRef: vault
  vaultAuthRef: finance-tracker
  mount: secret
  path: data/finance-tracker-dev
  destination:
    name: finance-tracker-secret
    create: true
  refreshAfter: 1h
