apiVersion: gateway.networking.k8s.io/v1
kind: HTTPRoute
metadata:
  name: telegram-server
  namespace: telegram-server-dev
spec:
  parentRefs:
    - name: cilium-gateway
      namespace: gateway-system
  hostnames:
    - telegram-server-dev.home.arpa
    - telegram-webhook-dev.internal
  rules:
    - matches:
        - path:
            type: PathPrefix
            value: /
      backendRefs:
        - name: telegram-server
          port: 8000