apiVersion: secrets.hashicorp.com/v1beta1
kind: VaultStaticSecret
metadata:
  name: telegram-server
  namespace: telegram-server-dev
spec:
  type: kv-v2
  vaultAuthRef: vault-auth
  mount: secret
  path: kubernetes/telegram-server/dev
  destination:
    name: telegram-server-secret
    create: true
  refreshAfter: 1h
