tempo:
  repository: grafana/tempo
  tag: "3.0.3"

  server:
    http_listen_port: 3200

  receivers:
    otlp:
      protocols:
        grpc:
          endpoint: "0.0.0.0:4317"
        http:
          endpoint: "0.0.0.0:4318"

  storage:
    trace:
      backend: local
      local:
        path: /var/tempo/traces
      wal:
        path: /var/tempo/wal

persistence:
  enabled: true
  size: 20Gi
  storageClassName: local-path

resources:
  requests:
    cpu: 100m
    memory: 256Mi
  limits:
    memory: 1Gi