apiVersion: secrets.hashicorp.com/v1beta1
kind: VaultStaticSecret
metadata:
  name: ghcr-secret
spec:
  type: kv-v2
  vaultAuthRef: vault-auth
  mount: secret
  path: global/ghcr
  destination:
    name: ghcr-secret
    create: true
    type: kubernetes.io/dockerconfigjson
  refreshAfter: 1h