alertmanager:
  alertmanagerSpec:
    storage:
      volumeClaimTemplate:
        spec:
          accessModes:
            - ReadWriteOnce
          resources:
            requests:
              storage: 2Gi
          storageClassName: local-path

grafana:
  persistence:
    enabled: true
    size: 5Gi
    storageClassName: local-path

  grafana.ini:
    plugins:
      preinstall_auto_update: false

  additionalDataSources:
    - name: Tempo
      type: tempo
      access: proxy
      url: http://tempo.monitoring.svc.cluster.local:3200
      isDefault: false

prometheus:
  prometheusSpec:
    serviceDiscoveryRole: EndpointSlice
    serviceMonitorSelectorNilUsesHelmValues: false
    storageSpec:
      volumeClaimTemplate:
        spec:
          accessModes:
            - ReadWriteOnce
          resources:
            requests:
              storage: 10Gi
          storageClassName: local-path