apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: finance-tracker-prod

resources:
  - ../../base
  - namespace.yaml
  - httproute.yaml
  - configmap.yaml

images:
  - name: ghcr.io/lkxben/finance-tracker-backend
    newTag: "1"
  - name: ghcr.io/lkxben/finance-tracker-frontend
    newTag: "1"