apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: finance-tracker-prod

resources:
- ../../base
- namespace.yaml
- httproute.yaml
- configmap.yaml
- serviceaccount.yaml
- vault-auth.yaml
- vault-connection.yaml
- vault-rbac.yaml
- vault-secret.yaml

images:
- name: ghcr.io/lkxben/finance-tracker-backend
  newName: ghcr.io/lkxben/finance-tracker-backend
  newTag: 9fca365
- name: ghcr.io/lkxben/finance-tracker-frontend
  newName: ghcr.io/lkxben/finance-tracker-frontend
  newTag: 9fca365
