apiVersion: secrets.hashicorp.com/v1beta1
kind: VaultAuth
metadata:
  name: finance-tracker
  namespace: finance-tracker-prod
spec:
  vaultConnectionRef: vault
  method: kubernetes
  mount: kubernetes
  kubernetes:
    role: vso-finance-tracker-prod
    serviceAccount: vault-auth
