apiVersion: v1
kind: Service
metadata:
  name: headscale-node-exporter
  namespace: monitoring
  labels:
    app.kubernetes.io/name: headscale-node-exporter
spec:
  ports:
    - name: metrics
      port: 9100
      targetPort: 9100
---
apiVersion: v1
kind: Endpoints
metadata:
  name: headscale-node-exporter
  namespace: monitoring
subsets:
  - addresses:
      - ip: 192.168.20.30
    ports:
      - name: metrics
        port: 9100
---
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: headscale-node-exporter
  namespace: monitoring
spec:
  selector:
    matchLabels:
      app.kubernetes.io/name: headscale-node-exporter
  endpoints:
    - port: metrics
      interval: 30s
      path: /metrics