apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - compute-node-exporter.yaml
  - headscale-node-exporter.yaml
  - jenkins-agent-node-exporter.yaml
  - jenkins-node-exporter.yaml
  - npm-node-exporter.yaml
  - obsync-node-exporter.yaml
  - ollama-node-exporter.yaml
  - opnsense-node-exporter.yaml
  - pihole-node-exporter.yaml
  - postgres-node-exporter.yaml
  - pve-exporter.yaml
  - pve-node-exporter.yaml
  - rabbitmq-node-exporter.yaml
  - vault-node-exporter.yaml