apiVersion: v1
kind: Service
metadata:
  name: vault-node-exporter
  namespace: monitoring
  labels:
    app.kubernetes.io/name: vault-node-exporter
spec:
  ports:
    - name: metrics
      port: 9100
      targetPort: 9100
---
apiVersion: discovery.k8s.io/v1
kind: EndpointSlice
metadata:
  name: vault-node-exporter
  namespace: monitoring
  labels:
    kubernetes.io/service-name: vault-node-exporter
addressType: IPv4
ports:
  - name: metrics
    protocol: TCP
    port: 9100
endpoints:
  - addresses:
      - 192.168.20.90
    conditions:
      ready: true
---
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: vault-node-exporter
  namespace: monitoring
spec:
  selector:
    matchLabels:
      app.kubernetes.io/name: vault-node-exporter
  endpoints:
    - port: metrics
      interval: 30s
      path: /metrics