apiVersion: secrets.hashicorp.com/v1beta1
kind: VaultStaticSecret
metadata:
  name: finance-tracker-gmail
spec:
  type: kv-v2
  vaultAuthRef: finance-tracker
  mount: secret
  path: finance-tracker/gmail
  destination:
    name: finance-tracker-gmail-token
    create: true
  refreshAfter: 1h