apiVersion: v1
kind: ConfigMap
metadata:
  name: reminder-bot-config
  namespace: reminder-bot-prod
data:
  TELEGRAM_WEBHOOK_URL: "https://headscale.tail6fccd5.ts.net/reminder-bot/"
  LOG_LEVEL: "INFO"
  SCHEDULER_CHECK_INTERVAL: "30"
  API_PORT: "8000"
  API_HOST: "0.0.0.0"