apiVersion: secrets.hashicorp.com/v1beta1
kind: VaultStaticSecret
metadata:
  name: reminder-bot
  namespace: reminder-bot-prod
spec:
  type: kv-v2
  vaultAuthRef: vault-auth
  mount: secret
  path: kubernetes/reminder-bot/prod
  destination:
    name: reminder-bot-secret
    create: true
  refreshAfter: 1h
